name: CI
on:
 
  push:

  
  workflow_dispatch:
permissions: write-all
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github/CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java-kotlin
          build-mode: none
          queries: security-and-quality
      - name: Perform CodeQL Analysis
        uses:  github/codeql-action/analyze@v4
        with:
          category: "/language:java-kotlin"
  SCA:
  
    runs-on: ubuntu-latest
   
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: |
          mvn package
       
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: 'ms-catalog-content'
          path: '.'
          format: 'HTML'
          args: >
            --failOnCVSS 4
            --disableCentral
            
            
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: reportSCA
          path: ${{github.workspace}}/reports

  SCA_Analized:
    needs: SCA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download report
        uses: actions/download-artifact@v4
        with:
         name: reportSCA
      - name: analaisis
        run : |
         ls 
         vulnerabilities=$(jq -r '.dependencies[0].vulnerabilities[].severity' dependency-check-report.json)
         readarray -t bash_vul <<< "$vulnerabilities"
         echo "${bash_vul[@]}"
         for i in "${bash_vul[@]}"
         do
          if [[ "$i" == 'HIGH' || "$i" == 'CRITICAL' || "$i" == 'MEDIUM' ]]; then
           echo "Vulnerabilidades criticas por resolver"
           exit 1
          else
           echo "Sin vulnerabilidades criticas"
          fi
         done
  Build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: JDK
       uses: actions/setup-java@v4.2.1
       with:
         java-version: '17'
         distribution: 'temurin'
     - name: Mvn compile
       run: |
          mvn -q -DskipTests package
     - name: Jar
       run: |
          cp target/spring-petclinic-2.6.0-SNAPSHOT.jar spring-petclinic-2.6.0-SNAPSHOT.jar
          ls
       
     - name: Upload Maven artifacts
       uses: actions/upload-artifact@v4
       with:
          name: maven-build
          path: .
          
  docker-build:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name : Docker login
        uses: docker/login-action@v4.1.0
        with:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.PASS_DOCKER }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
         name: maven-build
         path: .
         run: ls
      - name : Docker build
        run: |
          docker build --tag andresbastidasgutierrez/pet-clinic:latest .
      - name : Analisis
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'andresbastidasgutierrez/pet-clinic:latest'
          format: table
          exit-code: 1
          vunl-type: 'os, library'
          severity: 'HIGH,CRITICAL,MEDIUM'
            
         

