name: CI
on:
 
  push:

  
  workflow_dispatch:
permissions: write-all
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: github/CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java-kotlin
          build-mode: none
          queries: security-and-quality
      - name: Perform CodeQL Analysis
        uses:  github/codeql-action/analyze@v4
        with:
          category: "/language:java-kotlin"
  SCA:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: Build
       run: |
         mvn package
     - name: Dependecy check
       uses: dependecy-check/Dependecy-Check_Action@1.1.0
       with:
          proyect: 'pet-clinic'
          path: '.'
          format: 'JSON'
          args: >
            --disableCentral
     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v7.0.1
       with:
         path: ${{github.workflow}}/reports
         
           
     
      
          
       
       

